const Data = [ 
    { 
        id: 1, 
        name: "volvo", 
        img:  "https://seeklogo.com/images/V/volvo-logo-BBD81B8EA6-seeklogo.com.png", 
        matched: false, 
    }, 
    { 
        id: 2, 
        name: "volvo", 
        img:  "https://seeklogo.com/images/V/volvo-logo-BBD81B8EA6-seeklogo.com.png", 
        matched: false, 
    }, 
    { 
        id: 3, 
        name: "bmw", 
        img:  "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/BMW.svg/2048px-BMW.svg.png", 
        matched: false, 
    }, 
    { 
        id: 4, 
        name: "bmw", 
        img:  "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/BMW.svg/2048px-BMW.svg.png", 
        matched: false, 
    }, 
    { 
        id: 5, 
        name: "toyota", 
        img:  "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Toyota_EU.svg/2560px-Toyota_EU.svg.png", 
        matched: false, 
    }, 
    { 
        id: 6, 
        name: "toyota", 
        img:  "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Toyota_EU.svg/2560px-Toyota_EU.svg.png", 
        matched: false, 
    }, 
    { 
        id: 7, 
        name: "mazda", 
        img:  "https://1000logos.net/wp-content/uploads/2019/12/Mazda_Logo.png", 
        matched: false, 
    }, 
    { 
        id: 8, 
        name: "mazda", 
        img:  "https://1000logos.net/wp-content/uploads/2019/12/Mazda_Logo.png", 
        matched: false, 
    }, 
    { 
        id: 9, 
        name: "nissan", 
        img:  "https://upload.wikimedia.org/wikipedia/commons/8/8c/Nissan_logo.png", 
        matched: false, 
    }, 
    { 
        id: 10, 
        name: "nissan", 
        img:  "https://upload.wikimedia.org/wikipedia/commons/8/8c/Nissan_logo.png", 
        matched: false, 
    }, 
    { 
        id: 11, 
        name: "lada", 
        img: "https://upload.wikimedia.org/wikipedia/en/1/12/Lada_company_logo.png", 
        matched: false, 
    }, 
    { 
        id: 12, 
        name: "lada", 
        img: "https://upload.wikimedia.org/wikipedia/en/1/12/Lada_company_logo.png", 
        matched: false, 
    }, 
    { 
        id: 13, 
        name: "subaru", 
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Subaru_%282019%29.svg/800px-Subaru_%282019%29.svg.png", 
        matched: false, 
    }, 
    { 
        id: 14, 
        name: "subaru", 
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Subaru_%282019%29.svg/800px-Subaru_%282019%29.svg.png", 
        matched: false, 
    },
    { 
        id: 15, 
        name: "mercedes", 
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Mercedes-Logo.svg/2048px-Mercedes-Logo.svg.png", 
        matched: false, 
    }, 
    { 
        id: 16, 
        name: "mercedes", 
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Mercedes-Logo.svg/2048px-Mercedes-Logo.svg.png", 
        matched: false, 
    },
    { 
        id: 17, 
        name: "kia", 
        img: "https://upload.wikimedia.org/wikipedia/commons/1/13/Kia-logo.png", 
        matched: false, 
    }, 
    { 
        id: 18, 
        name: "kia", 
        img: "https://upload.wikimedia.org/wikipedia/commons/1/13/Kia-logo.png", 
        matched: false, 
    },
    { 
        id: 19, 
        name: "ford", 
        img: "https://e7.pngegg.com/pngimages/508/395/png-clipart-cars-logo-brands-cars-logo-brands.png", 
        matched: false, 
    }, 
    { 
        id: 20, 
        name: "ford", 
        img: "https://e7.pngegg.com/pngimages/508/395/png-clipart-cars-logo-brands-cars-logo-brands.png", 
        matched: false, 
    },
    { 
        id: 21, 
        name: "audi", 
        img: "https://www.freepnglogos.com/uploads/audi-logo-28.png", 
        matched: false, 
    }, 
    { 
        id: 22, 
        name: "audi", 
        img: "https://www.freepnglogos.com/uploads/audi-logo-28.png", 
        matched: false, 
    },
    { 
        id: 23, 
        name: "vw", 
        img: "https://i.pinimg.com/originals/a3/45/66/a34566c7b7457245769385c8d40e93dd.png", 
        matched: false, 
    }, 
    { 
        id: 24, 
        name: "vw", 
        img: "https://i.pinimg.com/originals/a3/45/66/a34566c7b7457245769385c8d40e93dd.png", 
        matched: false, 
    },
    { 
        id: 25, 
        name: "buggati", 
        img: "https://pngimg.com/uploads/bugatti_logo/bugatti_logo_PNG14.png", 
        matched: false, 
    }, 
    { 
        id: 26, 
        name: "buggati", 
        img: "https://pngimg.com/uploads/bugatti_logo/bugatti_logo_PNG14.png", 
        matched: false, 
    },
    { 
        id: 27, 
        name: "ferrari", 
        img: "https://i.pinimg.com/originals/cd/36/19/cd3619f9e171f176bf0774017147170d.png", 
        matched: false, 
    }, 
    { 
        id: 28, 
        name: "ferrari", 
        img: "https://i.pinimg.com/originals/cd/36/19/cd3619f9e171f176bf0774017147170d.png", 
        matched: false, 
    },
]; 
export default Data;